name: recsys_training
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - cython=0.29.14
  - ipython=7.12.0
  - jupyterlab=1.2.6
  - lightfm=1.15
  - matplotlib=3.1.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=0.25.3
  - pip=20.0.2
  - python=3.7.5
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=45.1.0
  - statsmodels=0.11.0
  - pip:
    - "--editable=git+https://github.com/coreylynch/pyFM#egg=pyfm"
    - tqdm==4.41.0